@host = https://localhost:5044 
@hostId=dc16d820-a297-4618-88c4-570fedd91cdf
@token=  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ODM1OTRkNi0wYTEwLTRhZDQtODJhZS1jMzM4Yjk0NTE1M2UiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiNGJhNDc5ZTUtOTM4NS00NjM1LWE5MzAtOGM0MDg0MTMzZWQwIiwiZXhwIjoxNzUyMzYwNzMwLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.GoQrIM7pGncf3JjXi7Q3mVfOWzsViXq3sehfv4GS2DQ

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}