@host = https://localhost:5044 
@hostId=dc16d820-a297-4618-88c4-570fedd91cdf
@token=  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYjhhOTAxNS0xZThiLTQwNTktODJlYS05NjFmNmM4OGFlNTciLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiZTQ0YTU4MTAtNmIyYS00ZTllLWEyODAtNTk5ZjM2Y2IxMWZjIiwiZXhwIjoxNzUyMzY4ODA5LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.LCUR_wpsKEJyYKKGYHbdVAraQX3JBdrlIEJj3gylSPM

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}