@host = https://localhost:5044

GET  {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzY2JhNGVmNC1mMDg1LTQzMjYtYWExNi04YjJjNzAxNjM5ODAiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiMDYxNThkMTgtNGEyMS00Yzk4LWI3MWQtZTMzNjRhY2EzNDg0IiwiZXhwIjoxNzUyMTAzMTQ2LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.hKukRSxsTWwZjjlsW8RWRaS2qiOxkX6dkmDTaNrRsss
